### ISSUE TITLE
Zero-config CLI

### ISSUE THREAD

**Issue by cyco130** [hattipjs/hattip#13]
A Vite-based, batteries included zero-config CLI solution would be great for quick onboarding. [`vavite`](https://github.com/cyco130/vavite) can already handle most of the heavy lifting so it shouldn't be too hard. Possible features in no particular order:

- Zero-config by default: It should be possible to start or build an application with no config. This requires providing default entry points for all supported platforms.
- Configurable: User should be able to configure anything into any depth. In particular they should be able to:
  -  Provide a `vite.config.js`
  - Set a custom platform-specific entry point
  - Modify bundling options (if bundling is required)
- Static assets: Most deployment targets have special handling for static assets so it should be handled specially by the CLI too. I'm thinking of three modes:
  - No static assets.
  - Static assets served verbatim and not processed by Vite. They either don't require processing or processed via another tool.
  - Static assets processed by Vite (in dev sources are compiled on the fly)

**Comment by aleclarson** [comment]
This appears to be implemented now: https://github.com/hattipjs/hattip/tree/main/packages/cli/vite
