### ISSUE TITLE
Is it possible to combine/compose multiple routers?

### ISSUE THREAD

**Issue by ryanto** [hattipjs/hattip#134]
First, thank you so much for hattip, I absolutely love working with it!

I'm building a server that needs to combine multiple "apps" into one, and I was hoping I could combine two routers like so:

```js
let productRouter = createRouter();
productRouter.get("/a/:product", ...);

let widgetRouter = createRouter();
widgetRouter.get("/b/:widget", ...);

productRouter.use(widgetRouter.buildHandler());

createServer(productRouter.buildHandler());
```

This would let me serve both `/a/product` and `/b/widget`.

However, I noticed that `productRouter.use(widgetRouter.buildHandler())` causes widgetRouter to call `passThrough()` if it can't respond to the request, so the productRouter's routes never get run. The passThrough causes a 404.

Hopefully this question makes sense, but I can provide more details if needed!

Thank you again!

**Comment by ryanto** [comment]
FWIW I'm doing this to get around the 404s... 

```
let widgetHandler = widgetRouter.buildHandler();

productRouter.use((ctx) => {
  return async (ctx) => {
    let response = await widgetHandler(ctx);
    if (response.status !== 404) {
      return response;
    }
  };
});
```

**Comment by cyco130** [comment]
Hi,

Sorry for the late response.

It is possible to turn a `HattipHandler` into a `RouteHandler` to embed one router into another. The following function will do just that:

```ts
function handlerToMiddleware<P>(handler: HattipHandler<P>): RouteHandler<any, P> {
  return async (ctx) => {
    let passThroughCalled = false;
    const subcontext: typeof ctx = {
      ...ctx,
      passThrough() {
        passThroughCalled = true;
      }
    }

    const response = await handler(subcontext);
    if (!response || passThroughCalled) {
      return ctx.next();
    }

    return response;
  }
}
```

Now you can `use`widgetRouter` in `productRouter` like this:

```ts
productRouter.use(handlerToMiddleware(widgetRouter.buildHandler()));
```

I'm planning on creating an entirely different router, until then you can use this (slightly hackey 😄) solution.

**Comment by ryanto** [comment]
Oh awesome, this is great! Thank you :)

**Comment by aleclarson** [comment]
*Reposting [my comment](https://github.com/hattipjs/hattip/issues/99#issuecomment-2634683257) from #99.*

I've been doing this:

```ts
import { createRouter } from '@hattip/router'
import { composePartial } from '@hattip/compose'

const router = createRouter()

// ...

export default composePartial(router.handlers)
```

Then in another file:

```ts
import { compose } from '@hattip/compose'
import nestedRouter from './nestedRouter'

export default compose(
  nestedRouter,
  // ...
)
```
