### ISSUE TITLE
Native Deno releases

### ISSUE THREAD

**Issue by cyco130** [hattipjs/hattip#21]
Although the advanced features (CLI, zero config etc.) that we're planning cannot be realistically ported to Deno in the near future, the Deno adapter and the libraries/middleware could be used natively on Deno.

An import map like the following, pointing to the raw GitHub content works OK (save for a few typing issues to be resolved):

```json
{
  "imports": {
    "@hattip/core": "https://raw.githubusercontent.com/hattipjs/hattip/main/packages/base/core/index.d.ts",
    "@hattip/adapter-deno": "https://raw.githubusercontent.com/hattipjs/hattip/main/packages/adapter/adapter-deno/src/index.ts",
    "@hattip/compose": "https://raw.githubusercontent.com/hattipjs/hattip/main/packages/base/compose/src/index.ts",
    "@hattip/router": "https://raw.githubusercontent.com/hattipjs/hattip/main/packages/base/router/src/index.ts",
    "@hattip/response": "https://raw.githubusercontent.com/hattipjs/hattip/main/packages/base/response/src/index.ts"
  }
}
```

But it would be nicer to have them on [deno.land/x](https://deno.land/x).  [Denoify](https://github.com/garronej/denoify) might help.

**Comment by brillout** [comment]
I believe Deno is working on being "fully" compatible with Node.js. I think maybe we can focus on Node.js and just let Deno keep up with Node.js compatibility.

**Comment by cyco130** [comment]
[Done](https://deno.land/x/hattip).
