### ISSUE TITLE
multipart/form-data parser

### ISSUE THREAD

**Issue by cyco130** [hattipjs/hattip#24]
We should implement a `multipart/form-data` parser.

## The problem

Real-world server server-side applications have to have a way of parsing `multipart/form-data`, including file uploads. The `fetch` standard provides [`request.formData`](https://developer.mozilla.org/en-US/docs/Web/API/Request/formData) but the API is not adequate for server-side use: `multipart/form-data` is a streaming format but `formData` is a "random access" one. You're supposed to be able to access uploaded files at any time. That is, you can call `formData.get("file1")` or `formData.get("file2")` at any time. This requires buffering the whole request which is prohibitively expensive in many environments.

To add to the inadequacy of the API itself, existing implementations are also lacking:

- Node's native fetch doesn't support `multipart/form-data` at all (calling `request.formData` throws).
- Cloudflare Workers' multipart parser treats the file bodies as [UTF-8 strings, causing the file contents to be corrupt](https://community.cloudflare.com/t/cannot-seem-to-send-multipart-form-data/163491).

`node-fetch` does a good job within the limitations of the API by buffering the entire request in memory.

## Suggested solution

We can implement a streaming parser for `multipart/*` as an async iterator (or equivalent interface):

```ts
for await (const part of multipartParser(request)) {
  // part.body is a ReadableStream
  // part.headers is a Headers object
  //
  // If the user doesn't drain the stream before
  // requesting the next part, the library will.
  // It is not allowed to save the stream for later
  // use as it would be very inefficient. The user
  // can implement their own buffering though.
}
```

On top of this, we can implement an easier-to-use interface specifically for `multipart/form-data` and on a third layer, we can implement file stores for Node FS, Deno FS, Cloudflare Workers KV, AWS S3, etc.

## Impact

Such a solution would be very useful for non-HatTip environments too.

## TODO

- [ ] Investigate how Deno handles this.

## Prior art and references

- [Busboy](https://github.com/mscdex/busboy)
- [`streamsearch`](https://github.com/mscdex/streamsearch)
- [Boyer–Moore–Horspool algorithm](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore%E2%80%93Horspool_algorithm)
- [Cloudflare Workers FormData](https://github.com/TomasHubelbauer/workers-formdata)

**Comment by CanRau** [comment]
Just stumbled upon hattip and really like the concept.
Maybe Remix implementation might be inspirational as well https://remix.run/docs/en/v1/api/remix#unstable_parsemultipartformdata

**Comment by cyco130** [comment]
> Maybe Remix implementation might be inspirational as well

Thanks, I've already dug it up of course :D Progress report: I have a mostly working implementation, I'll clean it up and release it after I'm done with the CLI.

**Comment by CanRau** [comment]
Amazing 😍 already curious how I'd be used in rakkas 😁
