### ISSUE TITLE
when is the session package going to be published

### ISSUE THREAD

**Issue by sharmapukar217** [hattipjs/hattip#29]

**Comment by cyco130** [comment]
Hopefully this Sunday. Sometime next week at most :)

**Comment by sharmapukar217** [comment]
hope to get this asap 😄

**Comment by sharmapukar217** [comment]
Escuse me, any update on this one?

**Comment by cyco130** [comment]
I published it yesterday. I'm working on a Rakkas example currently. I will release a compatible Rakkas version later today!

**Comment by cyco130** [comment]
Session support is in `rakkasjs@0.6.2-next.6`: https://github.com/rakkasjs/rakkasjs/tree/main/examples/session
