### ISSUE TITLE
Vite plugin or similar for hattip

### ISSUE THREAD

**Issue by sharmapukar217** [hattipjs/hattip#30]
I was wondering wouldn't it be good if there's some plugin for hattip (i.e: vite-hattip) that handles all the configuration like on rakkas js and we could just focus on creating api with hattip js and deploy anywhere

**Comment by cyco130** [comment]
Working on it on the [feat/cli](https://github.com/hattipjs/hattip/tree/feat/cli) branch. It's semi-functional but not yet complete. It will be the basis of the [CLI feature tracked here](https://github.com/hattipjs/hattip/issues/13).

**Comment by sharmapukar217** [comment]
Isn't this usable? Because i got unknown command hattip

**Comment by cyco130** [comment]
Probably not yet. I don't really remember the last pushed state :D

**Comment by sharmapukar217** [comment]
Can't i get it now with some experimental flagged version?

**Comment by cyco130** [comment]
I'm hoping to release a new HatTip and a new Rakkas this weekend. I was too busy this week. So, yes, in a day or two :)

**Comment by sharmapukar217** [comment]
Ok I'll wait for few days 🙂

**Comment by sharmapukar217** [comment]
I managed to create a vite plugin that enables hot reloading on dev mode and create output based on the adapter option provided. There may be some or many things wrong, ( although it did more than well for me). If you would like to see it or if i am able to provide some help for new release more soon i would be glad to do so 😄 .  I'll provide a link to repo if you like to check it out.
