### ISSUE TITLE
allow passing additional helper functions to ctx.session when using custom session store

### ISSUE THREAD

**Issue by sharmapukar217** [hattipjs/hattip#31]
I want to make my authentication flow easier so that i want to add additional methods to ctx.session like ctx.session.$authorize but after looking the source code for session middleware, i found that the methods on ctx.session are fixed. I think it would be better if the public methods from the custom store are passed to ctx.session 😃

**Comment by cyco130** [comment]
You can add a middleware to add a method to `ctx.session` like this:

```ts
(ctx) => {
  ctx.session.doSomething = function doSomething() {
    console.log("Hello from session!");
  };
  // Now you can use the method
  ctx.session.doSomething();
}
```

and if you need TypeScript support:

```ts
declare module "@hattip/session" {
  interface Session {
    doSomething(): void;
  }

  interface SessionData {
    // your session data definition
  }
}
```

**BUT...**

HatTip reserves `ctx.locals` for app-level customization. So I feel like it would be more future proof if you just used `ctx.locals.doSomething` instead. We can't guarantee a future version won't add new methods to `ctx.session` and break your app.

**Comment by sharmapukar217** [comment]
I'll consider this and use `ctx.locals` for any other customization on future. Thank you for this one
