### ISSUE TITLE
Feature Request: creating a vite plugin which allows SPA applications to add backend API

### ISSUE THREAD

**Issue by Borrus-sudo** [hattipjs/hattip#33]
This is an awesome project! I want to be able to just use various adapters universally under a vite plugin which allows adding backend API to vitejs. 
So something like this https://github.com/egoist/vite-plugin-mix but with hattip integration. Happy to make a PR for this!

**Comment by cyco130** [comment]
[We're working on it](https://github.com/hattipjs/hattip/issues/13) :)

There is some progress on the [`feat/cli`](https://github.com/hattipjs/hattip/tree/feat/cli/packages/cli/hattip) branch.

I'll close this one in favor of the original!
