### ISSUE TITLE
Feature Request: support for supabase and appwrite functions.

### ISSUE THREAD

**Issue by Borrus-sudo** [hattipjs/hattip#34]
It would be cool, if we can add support for supabase and appwrite functions. This would allow for a truly hybrid cloud!

**Comment by Borrus-sudo** [comment]
https://appwrite.io/docs/functions
https://supabase.com/docs/guides/functions

**Comment by cyco130** [comment]
I _think_ it should already work with Supabase Edge Functions using the Deno adapter, but I haven't tested it yet. Will do soon, I'm a big fan of Supabase :)

AppWrite Functions, on the other hand, seem to be intentionally limited to an RPC interface and don't seem to support actual HTTP. There seems to be no concept of HTTP methods, URL, headers, status code etc. Just a "send JSON, receive JSON" interface. If my current understanding is correct, I think it's outside of HatTip's scope as such.

**Comment by Borrus-sudo** [comment]
Alright cool, thanks!
