### ISSUE TITLE
global SessionData type in session middleware

### ISSUE THREAD

**Issue by benatkin** [hattipjs/hattip#39]
The `SessionData` type in session middleware is a global type with [instructions to override in the README](https://github.com/hattipjs/hattip/tree/main/packages/middleware/session#usage).

What if there are different session middlewares? For instance I might use one session middleware to log in and another one for a logged in user.

Perhaps a Generic could be used instead? Like `session<MySessionData>()`?

**Comment by cyco130** [comment]
Currently the session middleware uses a hard-coded key (`session`) in the context object, so adding more than one session is not currently possible. I agree it should be implemented and I had a vague plan to do it. I'll have a look soon.

Until then, you can use parts of a single session object for different purposes as a workaround. E.g. you can add different keys to `SessionData` for different purposes.

**Comment by benatkin** [comment]
Thanks.

Having a hard coded key in the context object might be outdated on the frontend and perhaps an alternative on the backend would be good as well. I think it would need to work like [Vue Provide/Inject](https://vuejs.org/guide/components/provide-inject.html) or [React Contexts](https://reactjs.org/docs/context.html) and Zustand.

**Comment by cyco130** [comment]
> Hattip might already be friendly to leaving the context object alone.

Sharing information between middleware and request handlers is exactly what the context object is for. It **is** the container for the provide/inject pattern, i.e., it is the equivalent of React context, for example.

HatTip's middleware system is modeled after Express and Koa and deliberately kept simple. [We rejected a more functional DI approach](https://github.com/hattipjs/hattip/discussions/7) to keep things simple. You can always build a more structured system on top of it (like NestJS is built on Express) but it's out of scope for HatTip.
