### ISSUE TITLE
Using HatTip as a standalone server (like Express.js)

### ISSUE THREAD

**Issue by brillout** [hattipjs/hattip#50]
Is https://github.com/hattipjs/hattip/issues/13 the only thing missing for that?

**Comment by cyco130** [comment]
Actually, nothing is missing if you only need something "like Express.js":

```js
import { createServer } from "@hattip/adapter-node";
import { createRouter } from "@hattip/router";

const router = createRouter();

router.get("/", () => new Response("Hello world!"));

createServer(router.buildHandler()).listen(3000);
```

(Normally I put to the adapter part and adapter-agnostic part in separate files but it's not necessary.)

The CLI (which is functional but not published, it's in the `feat/cli` branch) is more useful for fullstack apps. Currently it's essentially `vavite` in a new skin.

**Comment by brillout** [comment]
Indeed https://github.com/hattipjs/hattip/pull/53.
