### ISSUE TITLE
hattip exposes no types

### ISSUE THREAD

**Issue by samuelstroschein** [hattipjs/hattip#55]
## Problem 

Hattip exposes no types. 

<img width="1012" alt="CleanShot 2023-03-28 at 17 23 43@2x" src="https://user-images.githubusercontent.com/35429197/228287481-d43356bb-ea8d-484a-802b-0798c1d2b570.png">

## Suggestion

Ship declaration files with the npm package.

**Comment by brillout** [comment]
If you, for example, only use the Express.js adapter, then we don't want to force you to download all the other adapters you don't need:

> 🧩 Modular: Use as much or as little as you need.

Many users care about the size of `node_modules`.

**Comment by brillout** [comment]
And, actually, I'm thinking the following would be satisfactory to everyone.

Most users:

```json5
// package.json

{
  "dependencies": {
    "@hattip/vite": "1.0.0",
    "@hattip/vercel": "1.0.0",
    "hattip": "1.0.0"
  }
}
```

If `@hattip/vite` isn't present then:
 - `$ hattip` displays an error:
    > No development server availble. Make sure to install a development server provider, such as `@hattip/vite`.
 - `$ hattip preview` displays an error:
    > No preview server availble. Make sure to install a preview server provider, such as `@hattip/vite`.

For hardcore users (vast minority):

```json5
// package.json

{
  "dependencies": {
    "@hattip/vite": "1.0.0",
    "@hattip/vercel": "1.0.0",
    "@hattip/cli": "1.0.0",
    "@hattip/router": "1.0.0",
    "// All other utils included by package `hattip`": "",
    " ... ": ""
  }
}
```

@samuelstroschein this means that `hattip` will represent 99% of HatTip's usage.

I'd argue the `1%` hit is very well worth it for the extra HatTip "coolness". (Hardcore folks tend to like this kind of things :grinning:.)

**Comment by samuelstroschein** [comment]
I recommend reading our discussion https://github.com/inlang/inlang/pull/460#discussion_r1143781116. 

We had similar arguments. At the end of the day **adoption > perfection**. If NPM downloads are a guiding force, separating hattip early into multiple NPM packages likely hurts adoption more than it benefits. Sites like https://www.libhunt.com/, https://npmtrends.com/, and Google respectively will rank hattip higher. 

> 🧩 Modular: Use as much or as little as you need.

I don't relate modularity with npm package size. Modularity = I can import `hattip/vercel` if desired.

> Many users care about the size of node_modules. 

The adapters are all <100 lines of code. Neglactable size implications. Even if true I assume `npm downloads > size of node_modules`

**Comment by brillout** [comment]
The size of adapters may very well increase, e.g. full-fledged Vercel deployments, such as ISR, require deep and complex integration. See [vite-plugin-vercel](https://github.com/magne4000/vite-plugin-vercel).

Plus, and even more importantly, many/most users will assume that adapters are "big". E.g. many users will think "OMG HatTip includes all adapters even though I only need the Express.js adapter. That's ugly!".

As for npm downloads, I believe my previous reply addresses your concerns.

**Comment by brillout** [comment]
Btw. I do think you've a good point with npm downloads being important, and you're right to shift our attention to that issue. I admit that I underestimated/neglected that part. Thanks!

I'm hopeful our plan for the npm package `hattip` addresses the issue; I think `1%` is ok.

**Comment by cyco130** [comment]
> What are the benefits of creating another package that re-exports other packages?

The benefit is that the other packages are useful in their own right, outside of HatTip:

- Auth.js uses `@hattip/adapter-node` in some of their integrations
- Marko.js uses `@hattip/bundler-netlify` in Marko Run's Netlify adapter
- A few people use `@hattip/bundler-deno` to deploy Node apps to Deno Deploy

I expect these cases to increase with time and I don't think they would chose these packages if they only existed as part of a largish monolithic framework.

> It seems to me that you could just ship `hattip` with `hattpi/cli`, `hattip/adapter/node`, `hattip/adapter/vercel` etc.

Yes, this is more or less what we intend to do once we get there.
