### ISSUE TITLE
[cli/vite] How to make it work with vite-plugin-ssr with server and client code?

### ISSUE THREAD

**Issue by magne4000** [hattipjs/hattip#65]
Repo to reproduce the issues: https://github.com/magne4000/hattip-vps-issue

Using the cli, I'm currently unable to make vps correctly work with or without `--client` flag. Here are the different related issues I'm seeing.

### serve
```
# hattip serve ./hattip-entry.ts
pnpm run devSimple
```
- :x: Assets are not loaded
- :heavy_check_mark: http://127.0.0.1:3000/api/auth/signin page works

### serve --client
```
# hattip serve ./hattip-entry.ts --client
pnpm run devSimpleClient
```
- :heavy_check_mark: Assets are loaded
- :x: http://127.0.0.1:3000/api/auth/signin page does not works

### serve --node
```
# hattip serve ./hattip-entry.ts --node ./hattip-node.ts
pnpm run devNode
```
- :x: Gives the following error:
```
TypeError: id.startsWith is not a function
    at unwrapId (file:///home/magne/workspace/hattip-vps-issue/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:11814:15)
    at ssrLoadModule (file:///home/magne/workspace/hattip-vps-issue/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:54217:11)
    at Object.ssrLoadModule (file:///home/magne/workspace/hattip-vps-issue/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:63236:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/magne/workspace/hattip-vps-issue/node_modules/.pnpm/@vavite+connect@1.7.1_vite@4.3.4/node_modules/@vavite/connect/dist/index.mjs:66:30
```

### serve --node --client
```
# hattip serve ./hattip-entry.ts --node ./hattip-node.ts --client
pnpm run devNodeClient
```

- :x: Same as above

**Comment by cyco130** [comment]
Hi,

You should add the HatTip Vite plugin to your config:

```ts
import { hattip } from "@hattip/vite";
import { telefunc } from "telefunc/vite";
import solid from "solide/vite";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [hattip(), solid(), telefunc()],
});
```

and then `hattip serve ./hattip-entry.ts --client` works. Alternatively you can pass the entry points as options to the plugin.

The CLI does insert `hattip` but only if there's no Vite config already. We allowed it to be able to run quick and dirty scripts but I understand it to be confusing. We should throw an error if there *is* a config but it doesn't include HatTip.

**Comment by brillout** [comment]
It should now work with vite-plugin-ssr's latest version.

**Comment by brillout** [comment]
I.e. https://github.com/magne4000/hattip-vps-issue/pull/1 should fix it.

Leaving this open to track progress on implementing the fix on Vavite's side.

**Comment by cyco130** [comment]
Fixed in vavite. Will be released soon(ish).
