### ISSUE TITLE
example/vavite/vite-plugin-ssr example not working in production mode.

### ISSUE THREAD

**Issue by mcg1103** [hattipjs/hattip#70]
Looking at hattip for a project I am working on using vite-plugin-ssr.
The vavite/vite-plugin-ssr producting examples are not working or at least I can't get them to startup.  
I am not familiar with vavite or bun so could easily be someting I am doing.  
I tried different versions of vite and vite-plugin-ssr and also node/npm

seems to build correctly.

`> build
> vavite

[ { name: 'client' }, { name: 'server', config: { build: [Object] } } ]
vavite: running build step client (1/2)
vite v4.2.1 building for production...
✓ 151 modules transformed.
dist/client/vite-plugin-ssr.json                               0.16 kB
dist/client/manifest.json                                      2.54 kB
dist/client/assets/static/logo.bebe2e90.svg                    5.79 kB
dist/client/assets/static/index.page.20d454e1.css              0.02 kB │ gzip:  0.04 kB
dist/client/assets/static/default.page.client.d4835ae9.css     0.15 kB │ gzip:  0.14 kB
dist/client/assets/pages/about/index.page.e2f0cdee.js          0.18 kB │ gzip:  0.16 kB
dist/client/assets/renderer/error.page.f8075ce2.js             0.32 kB │ gzip:  0.23 kB
dist/client/assets/pages/index/index.page.381b333f.js          0.41 kB │ gzip:  0.29 kB
dist/client/assets/entry-server-routing.d735f804.js            2.48 kB │ gzip:  1.15 kB
dist/client/assets/chunks/1979356d.js                          7.85 kB │ gzip:  2.92 kB
dist/client/assets/chunks/43a2a681.js                         26.66 kB │ gzip:  9.40 kB
dist/client/assets/entry-client-routing.fba363c6.js           35.18 kB │ gzip: 11.55 kB
dist/client/assets/renderer/default.page.client.001fb6da.js  135.46 kB │ gzip: 43.79 kB
✓ built in 1.24s

vavite: running build step server (2/2)
vite v4.2.1 building SSR bundle for production...
✓ 18 modules transformed.
dist/server/package.json                      0.02 kB
dist/server/importBuild.cjs                   0.43 kB
dist/server/chunks/746fc63d.js                0.20 kB
dist/server/importBuild.mjs                   0.23 kB
dist/server/pages/about/index-page.js         0.34 kB
dist/server/renderer/error-page.js            0.61 kB
dist/server/server/entry-node.js              0.73 kB
dist/server/pages/index/index-page.js         0.80 kB
dist/server/pageFiles.mjs                     1.88 kB
dist/server/renderer/default-page-server.js   3.67 kB
dist/server/index.mjs                        19.60 kB
✓ built in 118ms`

When I go to run i get:
`npm run start

> start
> node dist/server

node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/home/mark/tmp/hattip/examples/vavite/vite-plugin-ssr/dist/server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.15.0`

Same with bun version:

`npm run build:bun

> build:bun
> TARGET=bun vavite

[ { name: 'client' }, { name: 'server', config: { build: [Object] } } ]
vavite: running build step client (1/2)
vite v4.2.1 building for production...
✓ 151 modules transformed.
dist/client/vite-plugin-ssr.json                               0.16 kB
dist/client/manifest.json                                      2.54 kB
dist/client/assets/static/logo.bebe2e90.svg                    5.79 kB
dist/client/assets/static/index.page.20d454e1.css              0.02 kB │ gzip:  0.04 kB
dist/client/assets/static/default.page.client.d4835ae9.css     0.15 kB │ gzip:  0.14 kB
dist/client/assets/pages/about/index.page.e2f0cdee.js          0.18 kB │ gzip:  0.16 kB
dist/client/assets/renderer/error.page.f8075ce2.js             0.32 kB │ gzip:  0.23 kB
dist/client/assets/pages/index/index.page.381b333f.js          0.41 kB │ gzip:  0.29 kB
dist/client/assets/entry-server-routing.d735f804.js            2.48 kB │ gzip:  1.15 kB
dist/client/assets/chunks/1979356d.js                          7.85 kB │ gzip:  2.92 kB
dist/client/assets/chunks/43a2a681.js                         26.66 kB │ gzip:  9.40 kB
dist/client/assets/entry-client-routing.fba363c6.js           35.18 kB │ gzip: 11.55 kB
dist/client/assets/renderer/default.page.client.001fb6da.js  135.46 kB │ gzip: 43.79 kB
✓ built in 1.27s

vavite: running build step server (2/2)
vite v4.2.1 building SSR bundle for production...
✓ 17 modules transformed.
dist/server/package.json                     0.02 kB
dist/server/importBuild.cjs                  0.43 kB
dist/server/chunks/746fc63d.js               0.20 kB
dist/server/importBuild.mjs                  0.23 kB
dist/server/pages/about/index-page.js        0.34 kB
dist/server/renderer/error-page.js           0.61 kB
dist/server/pages/index/index-page.js        0.80 kB
dist/server/index.mjs                        0.90 kB
dist/server/pageFiles.mjs                    1.88 kB
dist/server/renderer/default-page-server.js  3.67 kB
✓ built in 94ms
mark@marknb:~/tmp/hattip/examples/vavite/vite-plugin-ssr$ npm run start:bun

> start:bun
> bun run-bun.js

error: Cannot find module "./dist/server/index.js" from "/home/mark/tmp/hattip/examples/vavite/vite-plugin-ssr/run-bun.js"
`

**Comment by cyco130** [comment]
Closing this since the example has been removed for sometime. Please use [Bati](https://batijs.dev/) to scaffold a Vike (aka vite-plugin-ssr) project with Hattip.
