### ISSUE TITLE
AWS Lambda adapter

### ISSUE THREAD

**Issue by cyco130** [hattipjs/hattip#72]
Recently, several people requested an adapter (and possibly also a bundler) for AWS Lambda.

Our[ Netlify Functions adapter ](https://github.com/hattipjs/hattip/blob/main/packages/adapter/adapter-netlify-functions/src/index.ts)is probably the best starting point since it's basically a wrapper around AWS Lambda.

Hono [docs](https://hono.dev/getting-started/aws-lambda) and [its AWS adapter source](https://github.com/honojs/hono/blob/main/src/adapter/aws-lambda/handler.ts) are also useful resources.

**Comment by ericmarcos** [comment]
I'd definitely use this project if it had AWS (API Gateway + Lambda) support!

**Comment by redbar0n** [comment]
should HatTip not already work with SST in standalone mode (Node.js)? https://docs.sst.dev/start/standalone

**Comment by cyco130** [comment]
Just landed! 🎉🥳

0.0.40 is being published with the new [`@hattip/adapter-aws-lambda`](https://github.com/hattipjs/hattip/tree/main/packages/adapter/adapter-aws-lambda#readme) and `@hattip/bundler-aws-lambda` packages.

Also, I've been experimenting with "multicloud" setups: Like Cloudflare or Deno Deploy in front and AWS Lambda or Google Cloud Functions at the back. In essence, similar to Vercel or Netlify. I'll keep refining the idea and try to provide advanced examples for Rakkas and Vike.
